"""Generate synthetic AI Gateway usage data via FMAPI and load it into UC.

Simulates 14 days of inference-table payloads from a ~40-person org. Eight
latent prompt patterns are hidden in the traffic (the engine must rediscover
them) plus one-off noise prompts. Each pattern is generated by FMAPI as real
prompt-text variations, so clustering works on genuinely messy text rather
than templated strings.
"""
import json
import random
import sys
import uuid
from datetime import datetime, timedelta
from pathlib import Path

from common import CATALOG, SCHEMA, run_sql, sql_str
from promptgen import generate_prompts

random.seed(42)
OUT = Path(__file__).parent.parent / "app" / "data"
OUT.mkdir(parents=True, exist_ok=True)

# Latent patterns: (key, persona pool, generator brief, weekly frequency weight)
PATTERNS = [
    ("nl2sql", ["analyst", "pm"],
     "asking an LLM to write a SQL query against tables like orders, customers, sensor_events, "
     "revenue by region/month, churn cohorts. Vary phrasing, dialect mentions (Databricks SQL, Trino), "
     "column names, and sloppiness.", 9),
    ("incident_rca", ["sre", "engineer"],
     "asking an LLM to draft a root-cause-analysis or incident summary from pasted notes: outage "
     "timeline, impact, mitigation, action items. Vary incident types (latency spike, OOM, cert expiry, "
     "bad deploy, Kafka lag).", 7),
    ("support_reply", ["support"],
     "asking an LLM to draft a polite customer reply from a ticket description: refunds, login issues, "
     "API errors, feature requests, angry customers. Vary tone instructions.", 8),
    ("pr_summary", ["engineer"],
     "asking an LLM to summarize a code diff / PR for reviewers: what changed, risk, test coverage. "
     "Vary languages (Python, Go, Terraform) and detail levels.", 6),
    ("ticket_triage", ["support", "engineer"],
     "asking an LLM to classify/triage a Jira or support ticket: severity, team routing, dedupe "
     "against known issues, write a one-line summary.", 6),
    ("meeting_actions", ["pm", "manager"],
     "asking an LLM to turn pasted meeting notes into action items with owners and due dates, or a "
     "crisp recap email. Vary meeting types (standup, QBR, design review).", 5),
    ("doc_summarize", ["analyst", "pm", "manager", "engineer"],
     "asking an LLM to summarize a long document: design doc, vendor contract, research paper, "
     "runbook — into N bullets or an executive summary.", 5),
    ("log_regex", ["engineer", "sre"],
     "asking an LLM for help parsing logs or writing a regex/grok pattern: extract fields from nginx "
     "or app logs, explain a gnarly regex, convert to another flavor.", 4),
]
NOISE_BRIEF = ("one-off miscellaneous workplace prompts with NO common pattern: trivia, a poem for a "
               "coworker's farewell, travel question, unit conversion, random coding question, recipe.")

USERS = {
    "analyst":  [f"{n}@acme-corp.com" for n in ("maya.patel", "jon.weiss", "li.chen", "sara.kim", "omar.haddad", "tessa.brooks")],
    "engineer": [f"{n}@acme-corp.com" for n in ("dev.rao", "kate.olson", "mikhail.petrov", "ana.souza", "chris.doyle", "yuki.mori", "sam.akin", "nina.vogel")],
    "sre":      [f"{n}@acme-corp.com" for n in ("pat.murphy", "zoe.adler", "raj.iyer", "elena.diaz")],
    "support":  [f"{n}@acme-corp.com" for n in ("liam.walsh", "ivy.tran", "max.berg", "rosa.flores", "ken.ito")],
    "pm":       [f"{n}@acme-corp.com" for n in ("amy.ford", "tom.nagy", "lucia.rossi", "dan.okafor")],
    "manager":  [f"{n}@acme-corp.com" for n in ("ruth.lang", "vic.osei", "hana.sato")],
}
ENDPOINTS = ["databricks-claude-sonnet-4-6", "databricks-claude-haiku-4-5", "databricks-gpt-oss-120b"]
NOW = datetime(2026, 6, 8, 17, 0, 0)


def gen_variations(brief: str, n: int) -> list[str]:
    return generate_prompts(brief, n)


def main():
    rows = []
    for key, personas, brief, weight in PATTERNS:
        n = weight * 4  # ~4 weeks-ish of volume compressed into 14 days
        prompts = gen_variations(brief, n)
        print(f"  pattern {key}: {len(prompts)} prompts")
        for p in prompts:
            user = random.choice([u for pe in personas for u in USERS[pe]])
            ts = NOW - timedelta(days=random.uniform(0, 14))
            out_tok = random.randint(150, 900)
            rows.append({
                "request_id": str(uuid.uuid4()), "event_time": ts.isoformat(sep=" ", timespec="seconds"),
                "user_email": user, "endpoint_name": random.choice(ENDPOINTS),
                "prompt": p, "input_tokens": max(20, len(p) // 4 + random.randint(50, 400)),
                "output_tokens": out_tok, "latent_pattern": key,
            })
    noise = gen_variations(NOISE_BRIEF, 36)
    print(f"  noise: {len(noise)} prompts")
    for p in noise:
        user = random.choice([u for us in USERS.values() for u in us])
        ts = NOW - timedelta(days=random.uniform(0, 14))
        rows.append({
            "request_id": str(uuid.uuid4()), "event_time": ts.isoformat(sep=" ", timespec="seconds"),
            "user_email": user, "endpoint_name": random.choice(ENDPOINTS),
            "prompt": p, "input_tokens": max(20, len(p) // 4 + random.randint(20, 150)),
            "output_tokens": random.randint(60, 400), "latent_pattern": "noise",
        })
    random.shuffle(rows)
    (OUT / "gateway_usage.json").write_text(json.dumps(rows, indent=1))
    print(f"wrote {len(rows)} rows -> app/data/gateway_usage.json")

    print("loading into UC ...")
    run_sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA} COMMENT 'SkillForge: AI Gateway usage mining demo'")
    run_sql(f"""CREATE OR REPLACE TABLE {CATALOG}.{SCHEMA}.gateway_usage (
        request_id STRING, event_time TIMESTAMP, user_email STRING, endpoint_name STRING,
        prompt STRING, input_tokens INT, output_tokens INT)
        COMMENT 'Simulated AI Gateway inference-table payloads (SkillForge demo). latent_pattern column intentionally excluded — the engine must rediscover patterns.'""")
    B = 50
    for i in range(0, len(rows), B):
        vals = ",".join(
            f"({sql_str(r['request_id'])}, TIMESTAMP{sql_str(r['event_time'])}, {sql_str(r['user_email'])}, "
            f"{sql_str(r['endpoint_name'])}, {sql_str(r['prompt'])}, {r['input_tokens']}, {r['output_tokens']})"
            for r in rows[i:i + B])
        run_sql(f"INSERT INTO {CATALOG}.{SCHEMA}.gateway_usage VALUES {vals}")
        print(f"  inserted {min(i + B, len(rows))}/{len(rows)}")
    cnt = run_sql(f"SELECT count(*), count(DISTINCT user_email) FROM {CATALOG}.{SCHEMA}.gateway_usage")
    print(f"UC table ready: {cnt[0][0]} rows, {cnt[0][1]} users")


if __name__ == "__main__":
    sys.exit(main())
